def create_config(filename):

    f = open(filename, 'w')
    f.write('[header]\n\n')
    f.write('INSTRUMENT: INSTRUME\n')
    f.write('NFRAMES: NAXIS3\n')
    f.write('EXP_NO: ESO DET EXP NO\n')
    f.write('NDIT: ESO DET NDIT\n')
    f.write('PARANG_START: ESO ADA POSANG\n')
    f.write('PARANG_END: ESO ADA POSANG END\n')
    f.write('DITHER_X: None\n')
    f.write('DITHER_Y: None\n')
    f.write('DIT: None\n')
    f.write('LATITUDE: None\n')
    f.write('LONGITUDE: None\n')
    f.write('PUPIL: None\n')
    f.write('DATE: None\n')
    f.write('RA: None\n')
    f.write('DEC: None\n\n')
    f.write('[settings]\n\n')
    f.write('PIXSCALE: 0.027\n')
    f.write('MEMORY: 100\n')
    f.write('CPU: 1')
    f.close()
